# Generated by Django 2.1.5 on 2020-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryStats', models.TextField(default='')),
                ('genderStats', models.TextField(default='')),
                ('ageStats', models.TextField(default='')),
                ('asy_id', models.TextField(default='')),
                ('isIg', models.BooleanField(default=False)),
                ('text', models.TextField(default='')),
                ('createdOn', models.DateField()),
                ('privacyScope', models.TextField(default='')),
                ('minAge', models.TextField(default='')),
                ('maxAge', models.TextField(default='')),
                ('actor', models.TextField(default='')),
                ('countries', models.TextField(default='')),
                ('genders', models.TextField(default='')),
                ('snapshot', models.TextField(default='')),
                ('attachments', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('adType', models.TextField(default='')),
                ('linkToAd', models.TextField(default='')),
                ('mainAttachment', models.TextField(default='')),
                ('height', models.TextField(default='')),
                ('likeNum', models.FloatField(default=0.0)),
                ('commentsNum', models.FloatField(default=0.0)),
                ('shareNum', models.FloatField(default=0.0)),
            ],
        ),
    ]
