# Generated by Django 2.1.5 on 2020-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='createdOn',
            field=models.CharField(default='', max_length=250),
        ),
    ]
