# Generated by Django 2.1.5 on 2020-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbads', '0003_auto_20200314_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='attachmentTitle',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ad',
            name='imageUrl',
            field=models.CharField(default='', max_length=250),
        ),
    ]
