# Generated by Django 2.1.5 on 2020-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbads', '0005_remove_ad_attachmenttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='hasVideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='videoUrl',
            field=models.CharField(default='', max_length=250),
        ),
    ]
